language: julia
os:
  - linux
julia:
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
env:
  - PYTHON=""
before_install:
  - "pip install -U sklearn"
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

